app:
  name: ai_agent
  mode: dev
  port: 8080

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: ai_agent
  max_open: 50
  max_idle: 10

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0

deepseek:
  api_key: "sk-16cf87757eb345768d4ae7db8e6cd4e7"
  base_url: "https://api.deepseek.com/v1"
  model: "deepseek-chat"