app:
  name: ai_agent
  mode: dev
  port: 8080

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: ai_agent
  max_open: 50
  max_idle: 10

redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0